name: Generate Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_index:
    if: "!contains(github.event.head_commit.message, 'Update index.json')"  # Prevent infinite loops
    runs-on: ubuntu-latest

    steps:
      # 1. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the required Python version

      # 2. Install necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 3. Run the Python script to update index.json
      - name: Run Python script
        id: run_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python create_index.py

      # 4. Commit and push changes if index.json was updated
      - name: Commit and push changes
        if: steps.run_script.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Clone the repository with minimal data
          git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo

          # Navigate to the repository
          cd repo

          # Replace the existing index.json with the updated one
          cp ../index.json .

          # Check if index.json has changes
          git add index.json
          git commit -m "Update index.json" || echo "No changes to commit"

          # Push the changes back to the main branch
          git push origin main
