name: Generate Index
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_index:
    if: "!contains(github.event.head_commit.message, 'Update index.json')"  # Skip if the commit message is from this action
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.ACTION_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with the Python version you need (e.g., '3.9')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python create_index.py
        
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_PAT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Gunbot Index Generator"
          git add index.json
          git commit -m "Update index.json"
          git push "https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/${{ github.repository }}.git" HEAD:main
