name: Generate Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_index:
    if: "!contains(github.event.head_commit.message, 'Update index.json')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        id: run_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python create_index.py

      - name: Commit and push changes
        if: steps.run_script.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "Gunbot Index Generator"

          # Initialize a new Git repository
          git init
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          # Fetch the latest main branch to set the correct upstream
          git fetch origin main

          # Checkout main branch
          git checkout -b main origin/main

          # Add and commit index.json
          git add index.json
          git commit -m "Update index.json"

          # Push the changes
          git push -u origin main
