name: Generate Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with the Python version you need (e.g., '3.9')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python create_index.py
        
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json
          git commit -m "Update index.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/boekenbox/gunbot-backtesting-archive.git HEAD:main
